### ISSUE TITLE
Hardware/Software requirements

### ISSUE THREAD

**Issue by cgtobi** [frawau/aiobtname#2]
Hi François,

would you mind sharing the hardware/software requirements to get `aiobtname`working? I try to get this working on a Raspberry Pi zero. `aioblescan` works fine but `aiobtname` doesn't give me anything.

This is on Raspbian 9.4 wirh kernel version `4.14.52+ #1123` with Python 3.5.3.

Cheers,
cgtobi

**Comment by frawau** [comment]
Hi,

Sorry for the delay. I am currently on holiday.

I have not tried on a RPi Zero yet, On a RPi3 running Debian Stretch it works with the same hardware. Also on a RPi 2 with Debian. 

How do you run aiobtname?

Regards,
    François

**Comment by cgtobi** [comment]
Hi,

No problem.

I simply tried call `python3 -m aiobtname 0 12:34:56:78:90:ab`.

Enjoy your holiday.

Cheers,
Tobias

**Comment by cgtobi** [comment]
Nevermind, it works when run as `root`.

**Comment by frawau** [comment]
Sorry... I had totally forgotten about that ....  Glad to know it works.
